name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        run: rustup toolchain install stable

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run Clippy (default features)
        run: cargo clippy --all-targets -- -D warnings

      - name: Run Clippy (tokio feature)
        run: cargo clippy --all-targets --features tokio -- -D warnings

      - name: Run tests (default features)
        run: cargo test --all

      - name: Run tests (tokio feature)
        run: cargo test --all --features tokio

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run tarpaulin
        run: cargo tarpaulin --features tokio --out Xml
